apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksteste-8fc2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksteste-8fc2"
  template:
    metadata:
      labels:
        app: "aksteste-8fc2"
    spec:
      containers:
        - name: "aksteste-8fc2"
          image: "akstestebf19.azurecr.io/aksteste"
          ports:
          - containerPort: 80